formatting

diff --git a/packages/neovim.minimal/__gen/configure b/packages/neovim.minimal/__gen/configure
--- a/packages/neovim.minimal/__gen/configure
+++ b/packages/neovim.minimal/__gen/configure
@@ -3,13 +3,13 @@
 environment="$1"
 case "$environment" in
 "desktop")
-	DOT_PKG_TARGET="$HOME/.config/nvim.minimal"
-	;;
+  DOT_PKG_TARGET="$HOME/.config/nvim.minimal"
+  ;;
 "server")
-	DOT_PKG_TARGET="$HOME/.config/nvim"
-	;;
+  DOT_PKG_TARGET="$HOME/.config/nvim"
+  ;;
 *)
-	echo "Invalid environment: $environment"
-	exit 1
-	;;
+  echo "Invalid environment: $environment"
+  exit 1
+  ;;
 esac
